//! Markdown report generation for plan and migrate commands.

use std::path::Path;

use crate::migrate::MigrationOutcome;
use crate::model::{MigrationPlan, Project};
use crate::plan;

/// Render a Markdown report describing the migration plan.
pub fn plan_report(project: &Project, plan: &MigrationPlan) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Angular migration plan: v{} -> v{}\n\n",
        plan.from, plan.to
    ));

    out.push_str(&format!(
        "- Project: `{}`\n- Root: `{}`\n- Path: {}\n\n",
        project.package.name(),
        project.root.display(),
        plan.path()
            .iter()
            .map(|m| m.to_string())
            .collect::<Vec<_>>()
            .join(" -> ")
    ));

    for step in &plan.steps {
        out.push_str(&format!("## Angular {} -> {}\n\n", step.from, step.to));
        let notes = step.notes();
        let actions: Vec<_> = step
            .rules
            .iter()
            .filter(|r| !matches!(r, crate::model::MigrationRule::Note { .. }))
            .collect();
        if actions.is_empty() {
            out.push_str("_No automated changes for this step._\n\n");
        } else {
            out.push_str("### Automated changes\n\n");
            for a in &actions {
                out.push_str(&format!("- [ ] {}\n", plan::describe_rule(a)));
            }
            out.push('\n');
        }
        if !notes.is_empty() {
            out.push_str("### Manual steps\n\n");
            for n in &notes {
                out.push_str(&format!("- [ ] {}\n", n));
            }
            out.push('\n');
        }
    }

    if !plan.third_party.is_empty() {
        out.push_str("## Third-party dependencies\n\n");
        out.push_str("| Package | Current | Recommended | Reason |\n");
        out.push_str("|---|---|---|---|\n");
        for s in &plan.third_party {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                s.package, s.from, s.to, s.reason
            ));
        }
        out.push('\n');
    }

    out.push_str(
        "---\n\nGenerated by `angular-migrator`. Verify the result with `npm install` \
         and `ng build` after every step.\n",
    );
    out
}

/// Render a Markdown summary of a completed migration.
pub fn migrate_report(root: &Path, outcome: &MigrationOutcome, plan: &MigrationPlan) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Angular migration report: v{} -> v{}\n\n",
        plan.from, plan.to
    ));
    out.push_str(&format!(
        "Mode: {}\n\n",
        if outcome.dry_run {
            "dry run (no files written)"
        } else {
            "live"
        }
    ));

    out.push_str("## Summary\n\n");
    out.push_str(&format!(
        "- Files changed: {}\n",
        outcome.changed_files.len()
    ));
    if outcome.package_rewritten {
        out.push_str("- package.json rewritten\n");
    }
    if outcome.workspace_rewritten {
        out.push_str("- angular.json rewritten\n");
    }
    if outcome.control_flow_migrated > 0 {
        out.push_str(&format!(
            "- Control-flow directives migrated: {}\n",
            outcome.control_flow_migrated
        ));
    }
    out.push('\n');

    if !outcome.changed_files.is_empty() {
        out.push_str("## Changed files\n\n");
        for f in &outcome.changed_files {
            let rel = f.strip_prefix(root).unwrap_or(f);
            out.push_str(&format!("- `{}`\n", rel.display()));
        }
        out.push('\n');
    }

    if !outcome.third_party.is_empty() {
        out.push_str("## Third-party recommendations\n\n");
        out.push_str("| Package | Current | Recommended | Reason |\n");
        out.push_str("|---|---|---|---|\n");
        for s in &outcome.third_party {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                s.package, s.from, s.to, s.reason
            ));
        }
        out.push('\n');
    }

    if !outcome.notes.is_empty() {
        out.push_str("## Manual steps remaining\n\n");
        for n in &outcome.notes {
            out.push_str(&format!("- [ ] {}\n", n));
        }
        out.push('\n');
    }

    if !outcome.warnings.is_empty() {
        out.push_str("## Warnings\n\n");
        for w in &outcome.warnings {
            out.push_str(&format!("- {}\n", w));
        }
        out.push('\n');
    }

    out.push_str("---\n\nNext: run `npm install`, then `ng build` / `ng test`, and iterate.\n");
    out
}
